{{- if .Values.secret.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default .Release.Name }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.values }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
